### ISSUE TITLE
Python upgrade to 3.7.9 breaking EB deployment

### ISSUE THREAD

**Issue by jestepseamless** [aws/aws-elastic-beanstalk-cli-setup#124]
**1. Please specify the following:**
 - OS: [e.g. OS X, Ubuntu, Windows, etc.]: Ubuntu
 - Shell (Bash, PowerShell, Zsh, etc.): Bash

- [x] **I have reviewed the troubleshooting tips described [here]() and they do not solve my problem**

**2. Description**
Latest commit from 2 hours ago is breaking EB CLI deployment. The command line is saying python 3.7.9 can't be found.

We're running the bundle installer script in `/scripts/bundled_installer`

Breaking commit: https://github.com/aws/aws-elastic-beanstalk-cli-setup/commit/7f7f9c92762cf7622e355d9c19546fa8eb96a7d0
<img width="829" alt="Screen Shot 2022-01-20 at 10 04 49 PM" src="https://user-images.githubusercontent.com/61166718/150458827-3
<img width="673" alt="Screen Shot 2022-01-20 at 10 05 00 PM" src="https://user-images.githubusercontent.com/61166718/150458863-67262a9c-f744-456a-b259-385cd2a6a53b.png">
c658e3d-701f-4910-bec1-af50d051a58e.png">

**Comment by pankajvaghelav2** [comment]
Facing same problem.

**Comment by pankajvaghela** [comment]
Facing same problem. Checking out to commit prior to this change, before running the installer script. Look at 2nd line here.

          git clone https://github.com/aws/aws-elastic-beanstalk-cli-setup.git
          cd aws-elastic-beanstalk-cli-setup && git checkout 102025cb0d1d38e949fde2ca6455764c6f8475fb && cd ./../ 
          ./aws-elastic-beanstalk-cli-setup/scripts/bundled_installer

**Comment by halcarleton** [comment]
Hi @jestepseamless,

Thanks for reaching out and letting us know about this issue. The issue you are running into is caused by your local version of `pyenv` being outdated.

It looks like the version of pyenv that is installed by the install script was not appropriately upgraded in the latest release which could be responsible for the issue you ran into. This issue could also occur if you already had an older version of `pyenv` installed.

To resolve the issue you can upgrade the version of `pyenv` you are using to the latest version(`2.2.3`). You can find the `pyenv` upgrade instructions here: https://github.com/pyenv/pyenv#upgrading

We will work to make the appropriate updates to the install script and it's documentation.

**Comment by jestepseamless** [comment]
> Facing same problem. Checking out to commit prior to this change, before running the installer script. Look at 2nd line here.
> 
> ```
>       git clone https://github.com/aws/aws-elastic-beanstalk-cli-setup.git
>       cd aws-elastic-beanstalk-cli-setup && git checkout 102025cb0d1d38e949fde2ca6455764c6f8475fb && cd ./../ 
>       ./aws-elastic-beanstalk-cli-setup/scripts/bundled_installer
> ```

This is what I did too, and thanks @halcarleton we will look back into it.
