### ISSUE TITLE
No instructions on how to update

### ISSUE THREAD

**Issue by zlove** [aws/aws-elastic-beanstalk-cli-setup#31]
It would be nice if the README gave clear instructions on the best way to upgrade when using the eb cli installed via these scripts. There is conflicting guidance depending on where you look.

1. FAQ 4.7 in the README sort of talks about upgrading, but it is not clear if re-running the install script is recommended
2. The `eb` command itself outputs `Alert: An update to the EB CLI is available. Run "pip install --upgrade awsebcli" to get the latest version.`
3. [This page](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/eb-cli3-install.html) gives pretty clear instructions: `To upgrade to the latest version of the EB CLI, download the latest version of the EB CLI setup scripts and rerun the bundled installer.`.

Is (3) the recommended method? And is this equivalent to `git update` and then re-running `python scripts/ebcli_installer.py`? Or should I run `./scripts/bundled_installer`?

**Comment by rahulrajaram** [comment]
Hi @zlove ,

Thanks for bringing this up. To upgrade the EBCLI, you can simply re-run `python scripts/ebcli_installer.py`. Having the latest changes is recommended but not necessary because the behaviour of `ebcli_installer.py` has always been to upgrade the EBCLI if it has been installed.

We should document this approach in unambiguous terms in the README.

**Comment by zlove** [comment]
Thanks for the clarification @rahulrajaram
