### ISSUE TITLE
Installing with Python3

### ISSUE THREAD

**Issue by bezreyhan** [aws/aws-elastic-beanstalk-cli-setup#60]
**1. Please specify the following:**
 - OS: OSX
 - Shell: Bash

- [x] **I have reviewed the troubleshooting tips described [here]() and they do not solve my problem**

**2. Description**
Please describe the problem you are facing as precisely as possible in this section
I get the following issue when installing with python3 (it works fine with python2):
```
Traceback (most recent call last):
  File "/Users/bezreyhan/.ebcli-virtual-env/bin/eb", line 5, in <module>
    from ebcli.core.ebcore import main
ModuleNotFoundError: No module named 'ebcli'
```
In other words `python3 aws-elastic-beanstalk-cli-setup/scripts/ebcli_installer.py` does not work but `python aws-elastic-beanstalk-cli-setup/scripts/ebcli_installer.py` works fine.

I'm new to Python so it's been difficult trying to figure out what the cause is.

Thanks

**Comment by rahulrajaram** [comment]
Hi @bezreyhan ,

Thanks for reaching out, and the late response.

The reason `python3 aws-elastic-beanstalk-cli-setup/scripts/ebcli_installer.py` does not work as expected might be due to path-related issues. When `pip` installs software on your computer, it expects the libraries to be in a certain path.

Path-related problems can be very hard to reason about in Python, which is why this package also comes with a Python installer, which, in most cases, makes the process of subsequently installing the EBCLI seemless.
