### ISSUE TITLE
Does not write stdout when run with node js child process until process is finished.

### ISSUE THREAD

**Issue by brcnblc** [aws/aws-elastic-beanstalk-cli-setup#62]
**1. Platform:**
 - OS: Mac , NodeJs

**2. Description**

I use eb in a node js application to perform automatic deployment into AWS elasticbeanstalk environment. eb is called in an async function such as:

`subProcess = spawn(command, args, {shell:true});
`

Where command is 'eb' and args is eb arguments.

There are also following lines in the async function:

```
subProcess.on('data', data => console.log(`${data.toString()}`));
subProcess.stdout.on('data', data => console.log(`${data.toString()}`));
```
How ever, nothing is written out to terminal before some time has passes even it normally prints out messages about on going process.

Eg:
eb create <arguments> --nohang
Normally outputs following output line by line when it happens.
```
Creating application version archive "app-lorem-ipsum".
Uploading adminApp/app-lorem-ipsum.zip to S3. This may take a while.
Upload Complete.
```

If ran from nodejs.childprocess.spawn async function

They are all written out when upload is complete.

If --nohang is not used , user can not see anything about the whole process including events until all of the process is finished.

**Note** that the async function works normally with other long processing batch jobs presenting intermediate results immediately after sub process produces output.

This issue effects user experience, since information can be written out to terminal very late or at the end of the process.

Thanks and Best Regards

Bircan

**Comment by rahulrajaram** [comment]
Hi @brcnblc,

Thanks for reaching out and sorry for the late response. I am curious to know how it is that you are executing the Node JS file that invokes `eb`. Is it , for instance, inside a Bash file?

Thanks,
Rahul.

**Comment by brcnblc** [comment]
Hi Rahul,

No, it is not executed inside a bash. It is executed such as node
filename.js.

Best Regards

Bircan

**Comment by rahulrajaram** [comment]
I see. This behaviour is extraneous to `eb` and is possibly due to the programming environment (in this case Node JS, but I know this is also the case with Python). The communication of the output back to the parent process happens in a buffered fashion (i.e. after the `eb` process completes, as your observation suggests).

There is some discussion around this topic [here](https://stackoverflow.com/questions/14332721/node-js-spawn-child-process-and-get-terminal-output-live#answer-32872753). Basically, you would need polling logic in your node script that invokes `eb`.
